sudo: required
services:
  - docker

before_install:
  - docker pull gcr.io/cpp-projects/cpp-ci:1
script:
  - >
    docker run -v `pwd`:/cpp-pcp-client gcr.io/cpp-projects/cpp-ci:1 /bin/bash -c "
    wget https://github.com/puppetlabs/leatherman/releases/download/${LEATHERMAN_VERSION}/leatherman.tar.gz &&
    tar xzvf leatherman.tar.gz --strip 1 -C / &&
    cd /cpp-pcp-client &&
    cmake $EXTRA_VARS . &&
    mkdir dest &&
    make $TARGET DESTDIR=/cpp-pcp-client/dest VERBOSE=1 -j2 &&
    { [[ '$COVERALLS' != 'ON' ]] || coveralls --gcov-options '\-lp' -r . -b . -e src -e vendor >/dev/null || true; }
    "
  - if [[ $DO_RELEASE = true ]]; then tar czvf cpp-pcp-client.tar.gz `find dest -type f -print`; fi

env:
  global:
    - LEATHERMAN_VERSION=1.4.0
  matrix:
    - TARGET=cpplint
    - TARGET=cppcheck
    - TARGET="all test install ARGS=-V" DO_RELEASE=true EXTRA_VARS="-DBOOST_STATIC=ON -DBUILD_SHARED_LIBS=OFF"
    - TARGET="all test install ARGS=-V" EXTRA_VARS="-DBOOST_STATIC=ON -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON -DBUILD_SHARED_LIBS=OFF" COVERALLS=ON

deploy:
  provider: releases
  api_key:
    secure: Hz0wjDyko1lu/0OwBBGK3cR4B7Io9ure+skv+m1aVCUlYibKTrFvwPJJmGD/S92xwe+DqD7r09K4h0Du9MxIyew3sgxVPdM54sRweKq4vuvgmw018vzqyU+EEvCPQiXCYQ/UrQ/0IRiCxysA5b9zbW8G9/Qy2du7sXWgNklMx1w5K0u/GZD9+vzzq7BrrH2bAaSF7g+1fjsODH3ABqqNwLbUZ0E1cvn+In5rOEfWmsGGshCXaTB+zINOsGC0hSnoY/s/YTTWiELi88UasCpJQrd++1qMO447qIKRDo4OltfxCvHOytwvzBmDU30NM5iIXZEqfGYTKcSF84xGu6dde6D1YKAMBnTW8a65rWstC297pcP+NuowFUxBV5iu97joO7cHcYdzsz42vPhboehW9x8juf333ftNC21pfhoh8iXNT3/xtG4rwfjY3iX/UcLZiEh2O0Gnhjqc3rqO5HqqzytDfuDe1NXN+jhBXz44HvrRE4SGo74yUYVuRx4advIe2AZZdExVRfphP8E/ZUAmOLmbRGWM398lggStPruoheCmzPElb3ubiS74eYSBKYgjxVjkHB2FGzvjj0W19NgcXh6568ptiF60t4T9odI2vYZTAG5Gsj6d0LP1KvEHAiO89tiza/yI+QKb+xfr+dVDJer4gK9YBMKTimUUTstl3oI=
  file: cpp-pcp-client.tar.gz
  skip_cleanup: true
  on:
    repo: puppetlabs/cpp-pcp-client
    tags: true
    condition: $DO_RELEASE = true

notifications:
  email: false
